name: CI Python para Sistema de Locadora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4


    - name: Configurar o Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # Habilita o cache para as dependências

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint com flake8
      run: |
        # Para a execução se houver erros de sintaxe ou imports não definidos (erros F)
        # Permite alguns avisos de formatação (W), mas reporta a contagem
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Sai com status 0 (sucesso) se não houver erros mais graves. Para ser mais rígido, remova a parte a seguir.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Testar com pytest
      run: |
        PYTHONPATH=. pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install selenium    